config/routes.rb
Rails.application.routes.draw do

  resources :postulations

  get 'how_to_buy/instructions'
  get 'how_to_buy/condition'

  resources :buyers do
    member do
      get :active
      get :edit_register
      patch :update_register
    end
    collection do
      get :msg_edit
    end
  end

  get 'buyers/welcome'

  post '/admin/pay_offs/add_cuadre', to: 'admin/pay_offs#add_cuadre', as: :admin_pay_offs_add_cuadre

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
             path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register/:type'}
  #controllers: {sessions: 'user/sessions', registrations: 'user/registrations'},

  devise_scope :user do
    get '/users/login/:type', to: 'user/sessions#new', as: :new_user_type_session
  end

  resources :shopping_carts do
    collection do
      get :for_tomorrow
      get :deliveries
      get :show_deliveries_shopping_cart
    end
  end

  post '/shopping_carts/:id/remove_item/:item_id', to: 'shopping_carts#remove_item', as: :remove_item_cart
  post '/shopping_carts/:id/add_item', to: 'shopping_carts#add_item', as: :add_item_cart

  post '/shopping_carts/:id/save_list', to: 'shopping_carts#save_list', as: :save_list

  get '/shopping_carts/for_tomorrow/:id', to: 'shopping_carts#show_for_tomorrow', as: :show_for_tomorrow
  get '/shopping_carts/deliveries/:id', to: 'shopping_carts#deliveries_shopping_cart', as: :deliveries_shopping_cart
  get '/shopping_carts/show_deliveries_shopping_cart/:id', to: 'shopping_carts#show_deliveries_shopping_cart', as: :show_deliveries_shopping_cart

  post '/buyers/zone_addres', to: 'buyers#zone_addres', as: :zone_addres

  get "commanded_detail" => 'main#commanded_detail'
  get "no_active" => 'main#no_active'

  root to: 'main#index'
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  belongs_to :buyer

  has_many :shopping_cart_items
  has_many :packings
  accepts_nested_attributes_for :packings, :allow_destroy => true
  has_many :products, through: :shopping_cart_items


  def remove_item(shopping_cart_item)
    self.shopping_cart_items.destroy(shopping_cart_item)
    update_product_stock(shopping_cart_item, 'increase')
  end

  def amount_total_cart
    self.shopping_cart_items.amount_total_cart_item
  end

  def cost_total_cart
    self.shopping_cart_items.cost_total_cart_item
  end

  def add_item(item_params)
    product_id = item_params[:product_id]
    product = Product.find_by_id(product_id)
    if product.measuring_type == MeasuringType::UNIDAD
      item_params[:quantity] = item_params[:quantity].to_f.ceil
    end
    quantity = item_params[:quantity]
    item_params[:cost] = product.cost
    if product.product_available?(quantity)
      self.shopping_cart_items.create(item_params)
      update_product_stock(item_params, 'decrease')
    else
      return false, "availability"
    end
  end

  def validate_quantity(item_params)
    quantity = item_params[:quantity]
    product_id = item_params[:product_id]
    if Product.find_by_id(product_id).measuring_type == MeasuringType::PESO and quantity.to_f < ConfigSystem.last.min_quantity
      return false, "minimun"
    else
      add_item(item_params)
    end
  end

  def amount_minimum_shopping?
    self.amount_total_cart < ConfigSystem.last.min_total_cart
  end

  def update_product_stock(item_params, action)
    product_id = item_params[:product_id]
    quantity = item_params[:quantity]
    Product.find_by_id(product_id).update_stock(quantity, action)
  end

  def change_status_received(params)
    obs = params[:obs]
    delivery_price = params[:delivery_price]
    self.update_attributes(status_cart: StatusCart::RECIBIDO, received_at: Time.now, delivery_price: delivery_price, observation: obs)
  end

  def change_status_prepared
    self.update_attributes(status_cart: StatusCart::PREPARADO, prepared_at: Time.now)
  end

  def change_status_delivered
    self.update_attributes(status_cart: StatusCart::ENTREGADO, delivered_at: Time.now)
  end

  def change_status_sent
    self.update_attributes(status_cart: StatusCart::ENVIADO)
  end


  def self.in_zone(zone)
    self.joins(buyer: [domicile: [:delivery_route]]).where("delivery_routes.zone_id = ?", zone)
  end

  ransacker :get_zone,
    formatter: proc { |v|
      results = ShoppingCart.in_zone(v).map(&:id)
      results = results.present? ? results : nil
    }, splat_params: true do |parent|
    parent.table[:id]
  end


end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_filter :authenticate_user!
  before_action :extract_shopping_cart, only: [:remove_item, :add_item, :save_list]
  before_action :find_item, only: [:remove_item]
  before_action :get_current_user, except: [:remove_item, :add_item]
  before_action :get_time_now, except: [:remove_item, :add_item, :save_list]
  before_action :find_and_group_deliveries, only: [:deliveries, :deliveries_shopping_cart, :show_deliveries_shopping_cart]
  #mejorar este codigo

  def index
    @shopping_carts = @user.shopping_carts.where("status_cart > :start_statuscart AND status_cart < :end_statuscart AND shopping_carts.received_at < :dates", {start_statuscart: StatusCart::INICIADO, end_statuscart: StatusCart::ENTREGADO, dates: @t.strftime("%Y-%m-%d 16:30:00")}).order(id: :desc)
    @shopping_cart = @shopping_carts.first
  end

  def show
    @shopping_carts = @user.shopping_carts.where("status_cart > :start_statuscart AND status_cart < :end_statuscart AND shopping_carts.received_at < :dates", {start_statuscart: StatusCart::INICIADO, end_statuscart: StatusCart::ENTREGADO, dates: @t.strftime("%Y-%m-%d 16:30:00")}).order(id: :desc)
    @shopping_cart = @shopping_carts.find(params[:id])
  end
  
  def for_tomorrow
    @shopping_carts = @user.shopping_carts.where("status_cart = :statuscart AND shopping_carts.received_at >= :dates", {statuscart: StatusCart::RECIBIDO, dates: @t.strftime("%Y-%m-%d 16:30:00")}).order(id: :desc)
    @shopping_cart = @shopping_carts.first
  end

  def show_for_tomorrow
    @shopping_carts = @user.shopping_carts.where("status_cart = :statuscart AND shopping_carts.received_at >= :dates", {statuscart: StatusCart::RECIBIDO, dates: @t.strftime("%Y-%m-%d 16:30:00")}).order(id: :desc)
    @shopping_cart = @shopping_carts.find(params[:id])
  end

  def deliveries
  end

  def deliveries_shopping_cart
    @entregas_shopping_cart = @shopping_carts.where("DATE_TRUNC('day', delivered_at at time zone '-04:00') = ?", @entregas.keys[params[:id].to_i])
    @index_entrega = params[:id]
    @shopping_cart = @entregas_shopping_cart.first
  end

  def show_deliveries_shopping_cart
    @entregas_shopping_cart = @shopping_carts.where("DATE_TRUNC('day', delivered_at at time zone '-04:00') = ?", @entregas.keys[params[:index_entrega].to_i])
    @index_entrega = params[:index_entrega]
    @shopping_cart = @entregas_shopping_cart.find(params[:id])
  end

  def remove_item
    @shopping_cart.remove_item(@shopping_cart_item)
    render :status => 200, :json => {:shopping_cart => @shopping_cart}
  end

  def add_item
    a,b = @shopping_cart.validate_quantity(add_item_params)
    if a
      render :status => 200, :json => {:shopping_cart => @shopping_cart, :add => "true"}
    else
      render :status => 200, :json => {:shopping_cart => @shopping_cart, :add => "false", :reason => b}
    end
  end

  def save_list
    @params = obs_params
    @params[:delivery_price] = @user.domicile.delivery_route.zone.delivery_price
    @shopping_cart.change_status_received(@params)
    render :status => 200, :json => {:shopping_cart => @shopping_cart}
  end

  private
    def extract_shopping_cart
      @shopping_cart = find_or_create_shopping_cart
    end

    def find_or_create_shopping_cart
      if find_shopping_cart.blank?
        current_user.shopping_carts.create
      else
        find_shopping_cart
      end
    end

    def find_shopping_cart
      ShoppingCart.find_by_id(params[:id])
    end

    def find_item
      @shopping_cart_item = ShoppingCartItem.find_by_id(params[:item_id])
    end

    def add_item_params
      params.permit(:product_id, :quantity, :amount)
    end

    def obs_params
      params.permit(:obs)
    end

    def get_current_user
      @user = current_user
    end

    def get_time_now
      @t = Time.now.in_time_zone('Caracas')
    end

    def find_and_group_deliveries
      @shopping_carts = @user.shopping_carts.select(:id, :delivered_at, :delivery_price).where("status_cart > ? AND delivered_at > ?", StatusCart::ENVIADO, @t.midnight - 10.day ).order(delivered_at: :desc)
      @entregas = @shopping_carts.group_by{ |u| u.delivered_at.in_time_zone('Caracas').strftime('%d-%m-%Y') }
    end

end

app/views/shopping_carts/_deliveries.html.slim
.container-fluid.padding-side-zero
  .row
    .col-xs-12.col-md-4.shopping_carts
      h2.text-center Listas de mandados
      ul.nav.nav-tabs
        li
          = link_to "Para hoy", shopping_carts_path, class: "list-group-item"
        li
          = link_to "Para mañana", for_tomorrow_shopping_carts_path, class: "list-group-item"
        li.active
          a data-toggle="tab" href="#received" Recibidos


      div.tab-content
        div.tab-pane.fade.in.active id="received"
          - unless @shopping_carts.blank?
            p.text-center 
              | Mandados recibidos el dia:
            .list-group.text-center
              - @entregas.each_with_index do |cart, index|
                = link_to deliveries_shopping_cart_path(index), {class: "list-group-item "}
                  span
                    = cart[0]
          - else
            p.none_list
              | No tienes mandados para mostrar


    .col-xs-12.col-md-4.shopping_carts
      - unless @shopping_carts.blank?
        h2.text-center
          | Recibidos
        - unless @entregas_shopping_cart.blank?
          p
            | El 
            = @entregas.keys[@index_entrega.to_i]
          .list-group style="text-align: right"
            - @entregas_shopping_cart.each do |cart|
              = link_to  show_deliveries_shopping_cart_path(cart, index_entrega: @index_entrega), {class: "list-group-item "}
                span
                  = number_to_currency(cart.amount_total_cart, unit: 'BsF ', separator: ',', delimiter: '.')
                span.badge.id_cart
                  = cart.id

          table id="tabla" class="table table-striped"
            thead
              tr
                td Sub-total
                td
                  = number_to_currency(@entregas_shopping_cart.joins(:shopping_cart_items).sum("amount * quantity"), unit: 'BsF ', separator: ',', delimiter: '.')
              tr
                td Delivery
                td
                  = number_to_currency(@entregas_shopping_cart.last.delivery_price, unit: 'BsF ', separator: ',', delimiter: '.')
            tfoot
              tr
                td Total
                td
                  = number_to_currency(@entregas_shopping_cart.joins(:shopping_cart_items).sum("amount * quantity")+@entregas_shopping_cart.last.delivery_price, unit: 'BsF ', separator: ',', delimiter: '.')
        - else
          p
            | Selecciona un dia en recibidos para ver mas detalle

    .col-xs-12.col-md-4
      - unless @shopping_cart.blank?
        h2.text-center Productos
        = render "detail_shopping_cart"

app/views/shopping_carts/_detail_shopping_cart.html.slim
span
  | Mandados Nro.
  = " #{@shopping_cart.id}"
table id="tabla" class="table table-striped"
  thead
    tr
      th Descripcion
      th Precio
  tfoot
    tr
      td Total
      td
        = number_to_currency(@shopping_cart.amount_total_cart, unit: 'BsF ', separator: ',', delimiter: '.')
  tbody style="visibility: visible"
    - @shopping_cart.shopping_cart_items.each do |item|
      tr
        td
          = item.product.description
          br
            = " #{number_with_precision(item.quantity, precision: 3, separator: ',', delimiter: '.')} x #{number_to_currency(item.amount, unit: 'BsF ', separator: ',', delimiter: '.')}"
        td
          = " #{ number_to_currency(item.quantity*item.amount, unit: '', separator: ',', delimiter: '.')} "

app/views/shopping_carts/_today.html.slim
.container-fluid.padding-side-zero
  .row
    .col-xs-12.col-md-4.shopping_carts
      h2.text-center Listas de mandados
      ul.nav.nav-tabs
        li.active
          a data-toggle="tab" href="#today" Para hoy
        li
          = link_to "Para mañana", for_tomorrow_shopping_carts_path, class: "list-group-item"
        li
          = link_to "Recibidos", deliveries_shopping_carts_path, class: "list-group-item"

      div.tab-content
        div.tab-pane.fade.in.active id="today"
          - unless @shopping_carts.blank?
            .list-group
              - @shopping_carts.each do |cart|
                = link_to  shopping_cart_path(cart), {class: "list-group-item "}
                  span.badge
                    = number_to_currency(cart.amount_total_cart, unit: 'BsF ', separator: ',', delimiter: '.')
                  span.badge.id_cart
                    = cart.id
                  span
                    = cart.received_at.in_time_zone('Caracas').strftime("%d-%m-%Y")
            table id="tabla" class="table table-striped" 
              thead
                tr
                  td Sub-total
                  td
                    = number_to_currency(@shopping_carts.joins(:shopping_cart_items).sum("amount * quantity"), unit: 'BsF ', separator: ',', delimiter: '.')
                tr
                  td Delivery
                  td 
                    = number_to_currency(@shopping_carts.last.delivery_price, unit: 'BsF ', separator: ',', delimiter: '.')
              tfoot
                tr
                  td Total
                  td
                    = number_to_currency(@shopping_carts.joins(:shopping_cart_items).sum("amount * quantity")+@shopping_carts.last.delivery_price, unit: 'BsF ', separator: ',', delimiter: '.')
          - else
            p.none_list
              | No tienes mandados para hoy

    .col-xs-12.col-md-8
      - unless @shopping_carts.blank?
        h2.text-center Productos
        = render "detail_shopping_cart"

app/views/shopping_carts/_tomorrow.html.slim
.container-fluid.padding-side-zero
  .row
    .col-xs-12.col-md-4.shopping_carts
      h2.text-center Listas de mandados
      ul.nav.nav-tabs
        li
          = link_to "Para hoy", shopping_carts_path, class: "list-group-item"
        li.active
          a data-toggle="tab" href="#for_tomorrow" Para mañana
        li
          = link_to "Recibidos", deliveries_shopping_carts_path, class: "list-group-item"

      div.tab-content
        div.tab-pane.fade.in.active id="for_tomorrow"
          - unless @shopping_carts.blank?
            .list-group
              - @shopping_carts.each do |cart|
                = link_to show_for_tomorrow_path(cart), {class: "list-group-item "}
                  span.badge
                    = number_to_currency(cart.amount_total_cart, unit: 'BsF ', separator: ',', delimiter: '.')
                  span.badge.id_cart
                    = cart.id
                  span
                    = cart.received_at.in_time_zone('Caracas').strftime("%d-%m-%Y")
          - else
            p.none_list
              | No tienes mandados para mañana

    .col-xs-12.col-md-8
      - unless @shopping_carts.blank?
        h2.text-center Productos
        = render "detail_shopping_cart"

app/views/shopping_carts/deliveries.html.slim
= render "deliveries"

app/views/shopping_carts/deliveries_shopping_cart.html.slim
= render "deliveries"

app/views/shopping_carts/for_tomorrow.html.slim
= render "tomorrow"

app/views/shopping_carts/index.html.slim
= render "today"

app/views/shopping_carts/show.html.slim
= render "today"

app/views/shopping_carts/show_deliveries_shopping_cart.html.slim
= render "deliveries"

app/views/shopping_carts/show_for_tomorrow.html.slim
= render "tomorrow"