config/routes.rb
Rails.application.routes.draw do

  resources :postulations

  get 'how_to_buy/instructions'
  get 'how_to_buy/condition'

  resources :buyers do
    member do
      get :active
      get :edit_register
      patch :update_register
    end
    collection do
      get :msg_edit
    end
  end

  get 'buyers/welcome'

  post '/admin/pay_offs/add_cuadre', to: 'admin/pay_offs#add_cuadre', as: :admin_pay_offs_add_cuadre

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
             path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register/:type'}
  #controllers: {sessions: 'user/sessions', registrations: 'user/registrations'},

  devise_scope :user do
    get '/users/login/:type', to: 'user/sessions#new', as: :new_user_type_session
  end

  resources :shopping_carts do
    collection do
      get :for_tomorrow
      get :deliveries
      get :show_deliveries_shopping_cart
    end
  end

  post '/shopping_carts/:id/remove_item/:item_id', to: 'shopping_carts#remove_item', as: :remove_item_cart
  post '/shopping_carts/:id/add_item', to: 'shopping_carts#add_item', as: :add_item_cart

  post '/shopping_carts/:id/save_list', to: 'shopping_carts#save_list', as: :save_list

  get '/shopping_carts/for_tomorrow/:id', to: 'shopping_carts#show_for_tomorrow', as: :show_for_tomorrow
  get '/shopping_carts/deliveries/:id', to: 'shopping_carts#deliveries_shopping_cart', as: :deliveries_shopping_cart
  get '/shopping_carts/show_deliveries_shopping_cart/:id', to: 'shopping_carts#show_deliveries_shopping_cart', as: :show_deliveries_shopping_cart

  post '/buyers/zone_addres', to: 'buyers#zone_addres', as: :zone_addres

  get "commanded_detail" => 'main#commanded_detail'
  get "no_active" => 'main#no_active'

  root to: 'main#index'
end

app/models/buyer.rb
class Buyer < User
  has_one :buyer_info
  accepts_nested_attributes_for :buyer_info
  has_one :domicile
  accepts_nested_attributes_for :domicile

  has_many :shopping_carts

  def name
    self.buyer_info ? self.buyer_info.first_name : self.email
  end

  def fullname
    self.buyer_info ? self.buyer_info.fullname : self.name
  end

  def get_shopping_cart
    self.shopping_carts.last.blank? ? self.shopping_carts.create :
    self.shopping_carts.last.status_cart == StatusCart::INICIADO ? self.shopping_carts.last :  self.shopping_carts.create

    # if self.deliveries.last.blank? 
    #   self.deliveries.create 
    #   self.deliveries.last.shopping_carts.create
    # else
    #   now = Time.now.in_time_zone('Caracas')
    #   time_close = now.strftime("%Y-%m-%d 16:30:00")

    #   if now < time_close
    #     if self.deliveries.last.shopping_carts.last.status_cart == StatusCart::INICIADO
    #       self.deliveries.last.shopping_carts.last 
    #     else
    #       self.deliveries.last.shopping_carts.create
    #     end
    #   else
        

  end

  def get_shopping_cart_prepared
    self.shopping_carts.where(status_cart: StatusCart::PREPARADO)
  end

  def activate
    self.update_attributes(active: true)
  end

end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :find_buyer, only: [:active, :edit_register, :update_register]

  def new
    @buyer = Buyer.new
    @buyer.build_buyer_info
    @buyer.build_domicile
    # @routes = DeliveryRoute.all
    @routes = DeliveryRoute.all
    @zone = Zone.all
  end

  def create
    @buyer = Buyer.new(buyer_params)
    if @buyer.save
      render 'welcome', buyer: @buyer
      ActionCorreo.new_registered_user(@buyer).deliver_now
    else
      @routes = DeliveryRoute.all
      @zone = Zone.all
      render 'new'
    end  
  end

  def edit_register
    @email = params[:email]
    @routes = DeliveryRoute.all
    unless @buyer.active
      if @buyer.email == @email
        render 'to_correct'
      end
    else
      redirect_to root_path
    end
  end

  def update_register
    if @buyer.update(buyer_params)
      redirect_to action: :msg_edit
      ActionCorreo.edit_registered_user(@buyer).deliver_now
    else
      @routes = DeliveryRoute.all
      render 'to_correct'
    end
  end

  def msg_edit
  end

  def active
    @email = params[:email]
    unless @buyer.active
      if @buyer.email == @email
        @buyer.activate
        render 'activated'
        #ActionCorreo.active_new_user(@buyer).deliver_now
      end
    else
      render 'activated'
    end
  end

  def zone_addres
    @addres = DeliveryRoute.where(zone: params[:zone]).order(:other)
    render :json => @addres, methods: [:get_without_addres, :get_addres_full, :get_delivery_time]
  end

  private

  def find_buyer
    @buyer = Buyer.find_by_id(params[:id])
  end

  def buyer_params
    params.require(:buyer).permit(:email, :password, :password_confirmation, :active, buyer_info_attributes: [:id, :buyer_id, :first_name, :last_name, :phonenumber], domicile_attributes: [:id, :buyer_id, :delivery_route_id, :home])
  end

end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_addres_delivery.html.slim
#myModalAddres.modal.fade tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  .modal-dialog role="document"
    .modal-content
      .modal-header.text-center
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          | &times;
        h3 class="modal-title"
          | ¿ Donde te gustaria recibir tus mandados ?
      .modal-body
        .form-horizontal
          .form-group
            label.col-sm-3.control-label Zona
            div.col-sm-9
              = select_tag("zona", options_for_select(@zone.map {|r| [r.get_zone_full, r.id]}), { include_blank: true})
          .form-group
            label.col-sm-3.control-label Direccion
            div.col-sm-9
              = select_tag("addres", options_for_select({}), { include_blank: true})
              = link_to "No encuentro mi direccion", new_postulation_path, class: "col-sm-12 text-right direction_none"

      .modal-footer
        button.btn-sm.btn-m onclick="set_addres_unique()"
          | Siguiente

app/views/buyers/_modal_loading.html.slim
#myModalLoading.modal.loading.fade tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-keyboard="false" data-backdrop="static"

app/views/buyers/activated.html.slim
.welcome_register
  .container-fluid
    .row
      .col-xs-12
        h2.text-center Bienvenid@ a Mandados Delivery
      .col-xs-12.text-center
        p.text-center
          | Gracias por elegir nuestro servicio
        p.text-center
          | Tu cuenta de usuario se encuentra activa
          br
            | Ya puedes crear mandados
        p
          = link_to 'Ingresar', root_path

app/views/buyers/msg_edit.html.slim
.welcome_register
  .container-fluid
    .row
      .col-xs-12
        h2.text-center Registro editado con exito
      .col-xs-12.text-center
        p.text-center
          | Te enviaremos un correo a tu direccion de email para que verifiques
          br 
            | y confirmes los datos que ingresaste en el formulario
        p.text-center
          | Luego de confirmar los datos se activara tu cuenta 
          br
            | y podrás empezar a crear mandados

app/views/buyers/new.html.slim
= render "modal_loading"
= render "addres_delivery"
.form_registro
  div.container-fluid
    div.row
      div.col-md-12
        h2.text-center Registro
      div.col-md-12
        = form_for @buyer, :html => { class: 'form-horizontal', id: 'form_registro'} do |f|
          - if @buyer.errors.any?
            div id="error_explanation"
              p
                | Por favor:
              ul
                - @buyer.errors.messages.values.each do |msg|
                  - msg.each do |m|
                    li
                      | -
                      = m
          div.form-group
            label.col-sm-3.control-label Email
            div.col-sm-9
              = f.email_field :email, autofocus: true, class: "form-control", placeholder: "Introduce tu email"
          div.form-group
            label.col-sm-3.control-label Contraseña
            div.col-sm-5
              = f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Contraseña"
            p.col-sm-4.help-block Coloca entre 8 y 20 caracteres
          div.form-group
            label.col-sm-3.control-label Repetir Contraseña
            div.col-sm-5
              = f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Contraseña"
          = f.fields_for :buyer_info do |h|
            div.form-group
              label.col-sm-3.control-label Nombre
              div.col-sm-9
                = h.text_field :first_name, class: "form-control", placeholder: "Introduce tu nombre"
            div.form-group
              label.col-sm-3.control-label Apellido
              div.col-sm-9
                = h.text_field :last_name, class: "form-control", placeholder: "Introduce tu apellido"
            div.form-group
              label.col-sm-3.control-label Teléfono
              div.col-sm-5
                = h.text_field :phonenumber, class: "form-control", placeholder: "Introduce tu número de teléfono"
              p.col-sm-4.help-block Usa este formato: 9999-9999999
          = f.fields_for :domicile do |h|
            div.form-group
              label.col-sm-3.control-label Direccion
              div.col-sm-7
                = h.select :delivery_route_id, options_for_select({}), { include_blank: true}, id: "ruta"
                p.time.help-block
              a.col-sm-2 style="cursor: pointer; color: #ff3400;" onclick="select_zone()"
                | Cambiar
            div.form-group
              label.col-sm-3.control-label Casa o Apartamento
              div.col-sm-9
                = h.text_field :home, class: "form-control", placeholder: "Introduce tu número de Casa o Apartamento"
          button.btn-block.btn-sm.btn-m type="submit" Enviar

          /'data-time' => r.delivery_time.in_time_zone('Caracas').strftime("%I:%M %p")

javascript:

  $(document).ready(function() {

    jQuery.validator.addMethod("customphone", function(value, element) {
      return this.optional(element) || /^\d{4}-\d{7}$/.test(value);
    }, "Usa este formato: 9999-9999999");

    $('#myModalAddres').modal('show');
  });

    $('#form_registro').validate({
        rules: {
            'buyer[email]': {
              required: true,
              email: true
            },
            'buyer[password]': {
              required: true,
              minlength: 8
            },
            'buyer[password_confirmation]': {
              required: true,
              minlength: 8,
              equalTo: "#buyer_password"
            },
            'buyer[buyer_info_attributes][first_name]': {
              required: true
            },
            'buyer[buyer_info_attributes][last_name]': {
              required: true
            },
            'buyer[buyer_info_attributes][phonenumber]': {
              customphone: true,
              required: true
            },
            'buyer[domicile_attributes][delivery_route_id]': {
              required: true
            },
            'buyer[domicile_attributes][home]': {
              required: true
            }
        },
        messages: {
            'buyer[email]': {
              required: "Email requerido",
              email: "Especifique un email valido"
            },
            'buyer[password]': {
              required: "Contraseña requerido",
              minlength: "La contraseña debe tener entre 8 y 20 caracteres"
            },
            'buyer[password_confirmation]': {
              required: "Confirmacion de contraseña requerido",
              minlength: "La contraseña debe tener entre 8 y 20 caracteres",
              equalTo: "Las contraseñas no coinciden"
            },
            'buyer[buyer_info_attributes][first_name]': {
              required: "Nombre requerido"
            },
            'buyer[buyer_info_attributes][last_name]': {
              required: "Apellido requerido"
            },
            'buyer[buyer_info_attributes][phonenumber]': {
              required: "Teléfono requerido",
              customphone: "Usa este formato: 9999-9999999"
            },
            'buyer[domicile_attributes][delivery_route_id]': {
              required: "Ruta de entrega requerido"
            },
            'buyer[domicile_attributes][home]': {
              required: "Número de casa o apartamento requerido"
            }
        },
        highlight: function (element) {
            $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function (element) {
            element.text('OK!').addClass('valid')
                .closest('.form-group').removeClass('has-error').addClass('has-success');
        },
        submitHandler: function(form) {
          $('#myModalLoading').modal('show');
          form.submit();
        }
    });

  $('#zona').selectize({
    placeholder: 'Selecciona una zona'
  });

  $('#zona-selectized').attr('readonly', 'readonly');

  var xhr;
  var select_zone, $select_zone;
  var select_addre, $select_addre;

  var select_addres_unique, $select_addres_unique

  $select_zone = $( "#zona" ).change(function() {
    //if (!value.length) return;
    var zone = $( "#zona" ).val();
    select_addre.disable();
    select_addre.clearOptions();
    select_addre.load(function(callback) {
        xhr && xhr.abort();
        xhr = $.ajax({
            type: "POST",
            dataType: "json",
            data: {
              zone: zone
             },
            url: '/buyers/zone_addres/',
            success: function(results) {
                select_addre.enable();
                callback(results);
            },
            error: function() {
                callback();
            }
        })
    });
  });

  $select_addre = $('#addres').selectize({
      valueField: 'id',
      labelField: 'get_without_addres',
      placeholder: 'Encuentra tu urbanización, residencia, edificio u oficina ',
      searchField: ['get_without_addres','addres'],
      render: {
              option: function(item, escape) {
                  return '<div>' +
                      '<span class="title">' + escape(item.get_without_addres) + '</span>' +
                      '<span class="description">' + escape(item.addres) + '</span>' +
                  '</div>';
              }
          },
  });

  select_addre  = $select_addre[0].selectize;
  select_zone = $select_zone[0].selectize;
  select_addre.disable();


  $select_addres_unique = $('#ruta').selectize({
      valueField: 'id',
      labelField: 'get_addres_full'
  });

  select_addres_unique  = $select_addres_unique[0].selectize;
  select_addres_unique.disable();

  var select_zone = function(){
    $('#myModalAddres').modal('show');
  }

  var set_addres_unique = function(){
    select_addres_unique.disable();
    select_addres_unique.clearOptions();
       jsonObj = [];
       item = {};
       item ["id"] = $( "#addres" ).val();
       item ["get_addres_full"] = $select_addre[0].selectize['options'][select_addre.getValue()]['get_addres_full'];
       jsonObj.push(item);

    select_addres_unique.load(function(callback) {
      select_addres_unique.enable();
      callback(jsonObj);
    });
    $('#myModalAddres').modal('hide');
    select_addres_unique.setValue(jsonObj[0].id);
    var str = "";
    str += $select_addre[0].selectize['options'][select_addre.getValue()]['get_delivery_time'];
    if (str =="undefined") {
      $( "p.time" ).text( "Seleccione una direccion para ver la hora de entrega");
    } else {
      $( "p.time" ).text( "La hora de entrega aproximada es: " + str );
    }
  }

app/views/buyers/to_correct.html.slim
= render "modal_loading"
.form_registro
  div.container-fluid
    div.row
      div.col-md-12
        h2.text-center Registro
      div.col-md-12
        = form_for @buyer, url: update_register_buyer_path(@buyer), method: :patch, :html => { class: 'form-horizontal', id: 'form_registro'} do |f|
          - if @buyer.errors.any?
            div id="error_explanation"
              p
                | Por favor:
              ul
                - @buyer.errors.messages.values.each do |msg|
                  - msg.each do |m|
                    li
                      | -
                      = m
          = f.fields_for :buyer_info do |h|
            div.form-group
              label.col-sm-3.control-label Nombre
              div.col-sm-9
                = h.text_field :first_name, class: "form-control", placeholder: "Introduce tu nombre"
            div.form-group
              label.col-sm-3.control-label Apellido
              div.col-sm-9
                = h.text_field :last_name, class: "form-control", placeholder: "Introduce tu apellido"
            div.form-group
              label.col-sm-3.control-label Teléfono
              div.col-sm-5
                = h.text_field :phonenumber, class: "form-control", placeholder: "Introduce tu número de teléfono"
              p.col-sm-4.help-block Usa este formato: 9999-9999999
          = f.fields_for :domicile do |h|
            div.form-group
              label.col-sm-3.control-label Ruta de entrega
              div.col-sm-9
                = h.select :delivery_route_id, options_for_select(@routes.map {|r| [r.get_addres_full, r.id, 'data-time' => r.delivery_time.in_time_zone('Caracas').strftime("%I:%M %p")]}, @buyer.domicile.delivery_route.id), { include_blank: false}, class: "form-control"
            div.form-group
              label.col-sm-3.control-label Hora de entrega
              p.col-sm-9.time.help-block
            div.form-group
              label.col-sm-3.control-label Casa o Apartamento
              div.col-sm-9
                = h.text_field :home, class: "form-control", placeholder: "Introduce tu número de Casa o Apartamento"
          button.btn-block.btn-sm.btn-m type="submit" Enviar

javascript:

  $(document).ready(function() {

    jQuery.validator.addMethod("customphone", function(value, element) {
      return this.optional(element) || /^\d{4}-\d{7}$/.test(value);
    }, "Usa este formato: 9999-9999999");

    
  });

    $('#form_registro').validate({
        rules: {
            'buyer[email]': {
              required: true,
              email: true
            },
            'buyer[password]': {
              required: true,
              minlength: 8
            },
            'buyer[password_confirmation]': {
              required: true,
              minlength: 8,
              equalTo: "#buyer_password"
            },
            'buyer[buyer_info_attributes][first_name]': {
              required: true
            },
            'buyer[buyer_info_attributes][last_name]': {
              required: true
            },
            'buyer[buyer_info_attributes][phonenumber]': {
              customphone: true,
              required: true
            },
            'buyer[domicile_attributes][delivery_route_id]': {
              required: true
            },
            'buyer[domicile_attributes][home]': {
              required: true
            }
        },
        messages: {
            'buyer[email]': {
              required: "Email requerido",
              email: "Especifique un email valido"
            },
            'buyer[password]': {
              required: "Contraseña requerido",
              minlength: "La contraseña debe tener entre 8 y 20 caracteres"
            },
            'buyer[password_confirmation]': {
              required: "Confirmacion de contraseña requerido",
              minlength: "La contraseña debe tener entre 8 y 20 caracteres",
              equalTo: "Las contraseñas no coinciden"
            },
            'buyer[buyer_info_attributes][first_name]': {
              required: "Nombre requerido"
            },
            'buyer[buyer_info_attributes][last_name]': {
              required: "Apellido requerido"
            },
            'buyer[buyer_info_attributes][phonenumber]': {
              required: "Teléfono requerido",
              customphone: "Usa este formato: 9999-9999999"
            },
            'buyer[domicile_attributes][delivery_route_id]': {
              required: "Ruta de entrega requerido"
            },
            'buyer[domicile_attributes][home]': {
              required: "Número de casa o apartamento requerido"
            }
        },
        highlight: function (element) {
            $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function (element) {
            element.text('OK!').addClass('valid')
                .closest('.form-group').removeClass('has-error').addClass('has-success');
        },
        submitHandler: function(form) {
          $('#myModalLoading').modal('show');
          form.submit();
        }
    });
  $( "select" ).change(function() {
    var str = "";
    $( "select option:selected" ).each(function() {
      str += $(this).data("time");
    });
    if (str =="undefined") {
      $( "p.time" ).text( "Seleccione una ruta para ver la hora de entrega");
    } else {
      $( "p.time" ).text( "La hora de entrega aproximada es: " + str );
    }
  }).trigger( "change" );

app/views/buyers/welcome.html.slim
.welcome_register
  .container-fluid
    .row
      .col-xs-12
        h2.text-center Bienvenid@
      .col-xs-12.text-center
        p.text-center
          | Gracias por elegir nuestro servicio
        p.text-center
          | Para terminar el proceso de registro te enviaremos un correo a tu direccion de email
          br 
            | para verificar y confirmar los datos que ingresaste en el formulario
        p.text-center
          | Luego de confirmar los datos se activara tu cuenta 
          br
            | y podrás empezar a crear mandados